[package]
name = "metabot"
version = "0.1.0"
edition = "2018"

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]
